# k3d cluster create local --config=cluster/config.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
image: rancher/k3s:v1.29.1-k3s1
servers: 1
agents: 1
options:
  k3d:
    wait: true
    timeout: "120s"
    disableRollback: true
  k3s:
    extraArgs:
      - arg: --disable=traefik,metrics-server,servicelb
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
ports:
  - port: 8081:80
    nodeFilters:
      - loadbalancer
