name: Publish Helm Charts
on:
  push:
    branches:
      - master

jobs:
  publishHelmChart:
    name: Helm gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: git actions
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - name: Helm linting
      run: |
        ./test/lint.sh

    - name: Helm gh-pages
      uses: statcan/actions/helm-ghpages@master
      with:
        args: "drupal https://drupalwxt.github.io/helm-drupal"
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        SCRIPT_MODE: true

    - name: Helm gh-pages
      uses: statcan/actions/helm-ghpages@master
      with:
        args: "drupal7 https://drupalwxt.github.io/helm-drupal"
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        SCRIPT_MODE: true
